### ISSUE TITLE
Can't compile in UE 4.7. Error C3668 and 5 warnings

### ISSUE THREAD

**Issue by angelts** [AndrewScheidecker/BrickGame#10]
error C3668: 'FBrickChunkSceneProxy::DrawDynamicElements' : method with override specifier 'override' did not override any base class methods	F:\UnrealEngine Marketplace\BrickGame-master\Plugins\BrickGrid\Source\BrickGrid\Private\BrickRenderComponent.cpp	193	1	BrickGame

error : Failed to produce item: F:\UnrealEngine Marketplace\BrickGame-master\Plugins\BrickGrid\Binaries\Win64\UE4Editor-BrickGrid.dll	f:\UnrealEngine Marketplace\BrickGame-master\Intermediate\ProjectFiles\ERROR	BrickGame

**Comment by AndrewScheidecker** [comment]
I just pushed a commit that fixes this (and generally brings the source code up to date for UE4.7): https://github.com/AndrewScheidecker/BrickGame/commit/1c088c75be67016840801f1bfa34aec402ac2224

**Comment by angelts** [comment]
Yes, I compiled with UE 4.7 right now without errors. Thanks for the great and fast support
